name: GCC Tests

on: 
    push:
        branches: [ master, main ]
    pull_request:
        branches: [ master, main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                repository: ShaunFell/arXiv_RSS_Reader
                token: ${{ secrets.CI_SECRET || github.token }}
                path: arXiv-RSS-Reader
            
            - name: update
              id: update_database
              continue-on-error: true
              run: |
               sudo apt-get update
               sudo apt-get install build-essentials qt5-default

            - name: qmake
              id: qmake
              run: |
               cd arXiv-RSS-Reader
               qmake -o Makefile arXiv-RSS-Reader.pro

            - name: build
              id: build
              continue-on-error: false
              run: |
               cd arXiv-RSS-Reader
               make -j$(nproc)