name: GCC Tests

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                repository: ShaunFell/arXiv-RSS-Reader
                token: ${{ secrets.CI_SECRET || github.token }}
                path: arXiv-RSS-Reader
            
            - name: update
              id: update_database
              continue-on-error: true
              run: |
               sudo apt-get update
               suod apt-get install build-essentials qt5-default

            - name: build
              id: build
              continue-on-error: false
              run: |
               cd arXiv-RSS-Reader
               make -j$(nproc)